### ISSUE TITLE
[Bug] ServerListIndicators showing incorrect server count

### ISSUE THREAD

**Issue by RemagOfficial** [Vendicated/Vencord#3041]
### Discord Account

remagofficial

### What happens when the bug or crash occurs?

the server count at the top of the server list shows 98 but when trying to join a new server discord tells me I'm already in 100 and can't join the new server

### What is the expected behaviour?

i expect it to show the correct count

### How do you recreate this bug or crash?

i dont really know what triggered it but maybe it was because a server i was in got deleted without me leaving it first

### Errors

no errors about the plugin

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Osintedx** [comment]
A potential solution could be to modify the plugin to filter out deleted servers when updating the count, meaning if you leave a server what's expected is: It doesn't keep it on the count, instead it removes it off.

What's happening:

It remains, the author of the plugin has not added a filter to it, to remove servers from still showing if they're deleted, or if the user leaves the guild.

**Comment by Nuckyz** [comment]
Should be fixed by https://github.com/Vendicated/Vencord/commit/d70e0f27dcdaca24443d57b319fee2c0a8997501

**Comment by RemagOfficial** [comment]
has this been released yet, it still shows 98 instead of 100 for me

**Comment by Nuckyz** [comment]
> has this been released yet, it still shows 98 instead of 100 for me, i have tried joining new servers and discord tell me i need to leave one

Are you in the browser?

**Comment by RemagOfficial** [comment]
> > has this been released yet, it still shows 98 instead of 100 for me, i have tried joining new servers and discord tell me i need to leave one
> 
> Are you in the browser?
no, windows desktop app
