### ISSUE TITLE
[Feature Request] Update Shiki to 0.14.1

### ISSUE THREAD

**Issue by checkraisefold** [Vendicated/Vencord#632]
### Discord Account

checkraisefold#4108

### What is it that you'd like to see?

The only issue I've run into with ShikiCodeblocks is the lack of support for ANSI highlighting, which was added with https://github.com/shikijs/shiki/pull/386 and is available in Shiki 0.14.0/0.14.1. I use ANSI for some custom colored code blocks with Discord bots. This would be pretty useful to have.

### Request Agreement

- [X] This is not a plugin request

**Comment by Vendicated** [comment]
@Vap0r1ze

**Comment by Vap0r1ze** [comment]
Discord uses it's own HLJS language definition for it's ANSI support, and since there is no ANSI language in Shiki it should fall back to HLJS for this (and work). I tested this before [in the vencord server](https://discord.com/channels/1015060230222131221/1024286218801926184/1048531692069060679) and it looked like it worked:
![it working](https://user-images.githubusercontent.com/20448879/227629919-4190a4a3-2b30-4fdc-90ca-a32756c1e293.png)

**Comment by checkraisefold** [comment]
This is solved, seems to have been a temporary Discord bug?

**Comment by blane1257** [comment]
Seemingly not solved, I just ran into the same issue.
As rendered in vanilla:
![2023-11-13_06-12](https://github.com/Vendicated/Vencord/assets/34515731/c44e8a01-9759-44a1-ba6e-a8f8dca22160)
And in Shiki, regardless of highlight preference setting:
![2023-11-13_06-13](https://github.com/Vendicated/Vencord/assets/34515731/4070e603-9d2b-4990-9483-38ea78c730e9)

**Comment by checkraisefold** [comment]
> Seemingly not solved, I just ran into the same issue. As rendered in vanilla: ![2023-11-13_06-12](https://user-images.githubusercontent.com/34515731/282445178-c44e8a01-9759-44a1-ba6e-a8f8dca22160.png) And in Shiki, regardless of highlight preference setting: ![2023-11-13_06-13](https://user-images.githubusercontent.com/34515731/282445352-4070e603-9d2b-4990-9483-38ea78c730e9.png)

Seems like a separate bug where highlighting just breaks sometimes

**Comment by blane1257** [comment]
Highlight works just fine for Rust, same issue is still observed for ANSI, so its not highlighting just breaking entirely, it seemingly is an issue specific to ANSI. And especially weird that not even the HLJS fallback functions as intended.
![image](https://github.com/Vendicated/Vencord/assets/34515731/d84e0c2c-d666-4e31-86bf-08f3182dfaea)

**Comment by HypheX** [comment]
I can confirm that the syntax highlighting works fine on everything except ANSI.

**Comment by checkraisefold** [comment]
Can also confirm, ANSI seems to have re-broken everywhere I look, seems like the HLJS fallback is just not working?
